services:
  www:
    container_name: liminal-ui-docs
    build:
      context: ../..  # Ra√≠z del monorepo
      dockerfile: apps/www/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
